////
Included in:

- user-manual: Defining an Anchor
////

An anchor can be defined almost anywhere: on a section title or discrete heading (automatic), on a paragraph, on a block or inline image, on listing or literal block, on a phrase, and so forth.
Anchors on block elements are called IDs.
Anchors on inline elements are called inline anchors.

==== IDs

The preferred way to define an ID is to use the shorthand syntax:

.Assigning an ID to a paragraph using shorthand syntax
----
include::ex-xref.adoc[tag=block-id-shorthand]
----

The ID name can be any combination of lower case letters a-z, underscore _, hyphen -, period . and digits 0-9, but it must begin with an underscore or letter.

Good names: `photos`, `_photo1`, `photo-1`, `_6bottles`.

Bad names: `green bottles` (spaces not allowed), `sixes&sevens` ({amp} not allowed), `6_bottles` (can't begin  with a number), `Kevin` (don't use upper case).

This table shows the other (non-preferred) ways that IDs can be created:

.Defining an ID, alternative methods
[cols="<20a,<20a"]
|===

|
----
include::ex-xref.adoc[tag=block-id-brackets]
----
|Traditional.
Required if you want to supply an xreflabel.

|
----
[id="photos"]
Any block element here
----

|Macro. 
Allows attribute substitution in the name.

|
----
include::ex-xref.adoc[tag=anchor-header]
----

|Special location that works for section headings only.
It has no advantage over the preferred method, and is easily confused with inline anchors, so don't use it. 

|===

Section headings get automatically created IDs if you haven't explicitly assigned one, see <<internal-cross-references>>.

==== Inline anchors

Inline anchors can be defined in any paragraph text.
The anchors in the text get replaced with invisible anchor points in the output.

As with block IDs, the preferred syntax is the shorthand form:

.Defining an inline anchor using shorthand syntax
----
include::ex-xref.adoc[tag=anchor-shorthand]
----

but there are several alternatives:

[cols="<20a,<20a"]
.Defining an inline anchor, alternative methods
|===

|
----
include::ex-xref.adoc[tag=anchor-brackets]
----
|Traditional.
Required if you want to supply an xreflabel.

|
----
include::ex-xref.adoc[tag=anchor-macro]
----

|Macro.
Allows attribute substitution in the name.

|===


NOTE:
Be careful where you put the anchor; it must be somewhere that receives the macro substitution.
If text content doesn't belong somewhere, neither does an inline anchor point.
For example, you would not put an anchor in front of a list item:

.Wrong position for an anchor ID in front of a list item.
----
include::ex-xref.adoc[tag=anchor-wrong]
----

Instead, you would put it at the very start of the text of the list item:

.Defining an inline anchor on a list item
----
include::ex-xref.adoc[tag=anchor-list]
----

Similarly for a heading:

.Adding additional anchors to a section
----
include::ex-xref.adoc[tag=anchor-header-extra]
----

CAUTION: If you add additional anchors to a section title, make sure you also assign an explicit ID to that section.
Otherwise, the anchor tag gets caught up in the generated ID.
See {issue-ref}/840[#840] for details.

==== Customizing the link text

It's possible to customize the text that will be used in the cross reference link (called `xreflabel`).
If not defined, Asciidoctor does it best to find suitable text (the solution differs from case to case).
In case of an image, the image caption will be used.
In case of a section header, the text of the section's title will be used.
For inline anchors, the link text is just `[label]`, so you almost always want to add an `xreflabel` to inline anchors.

To define the `xreflabel`, add it in the anchor definition right after the ID (separated by a comma).

.An anchor ID with a defined xreflabel. The xreflabel will be used as link text instead of the caption.
----
include::ex-xref.adoc[tag=anchor-xreflabel]
----

See <<Customizing the Cross Reference Text>> for other ways to change the link text.

